export const POSITIVE_KEYWORDS = [
    "looking for",
    "need",
    "hiring",
    "wanted",
    "editor",
    "editing",
    "video editor",
    "youtube editor",
    "shorts editor",
    "reels editor",
    "podcast editor",
    "video editing",
    "content creator",
    "creator",
    "youtube",
    "shorts",
    "reels",
    "tiktok",
    "instagram",
    "long term",
    "paid",
    "budget",
    "commission",
    "freelancer",
    "freelance",
    "remote",
    "help wanted"
];

export const NEGATIVE_KEYWORDS = [
    "for hire",
    "available for hire",
    "my portfolio",
    "showreel",
    "rate my",
    "feedback",
    "tutorial",
    "how do i",
    "question",
    "discussion",
    "free",
    "volunteer",
    "looking for feedback",
    "my first video",
    "watch my",
    "subscribers",
    "views",
    "algorithm"
];